# Generated by Django 2.2.5 on 2019-09-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app1',
            options={'verbose_name': '应用1', 'verbose_name_plural': '应用1'},
        ),
        migrations.AlterField(
            model_name='app1',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
    ]
